// lib/codegen.ts
// Generate reproducible Python (pandas) and R scripts that mirror what the user
// did in the app: load → select variables → clean → EDA → shape-specific bit.

import type { CleaningAction } from "./cleaning";
import type { DataShape } from "./shape";

export interface CodegenOptions {
  fileName: string;
  isExcel: boolean;
  sheetName?: string;
  excluded: string[];
  actions: CleaningAction[];
  shape: DataShape;
  entityCol?: string;
  timeCol?: string;
  valueCol?: string;
  maWindow?: number;
  /** Dependent variable for the multiple-regression block (optional). */
  regTarget?: string;
  /** Entity column → emit a fixed-effects regression instead of pooled OLS. */
  regEntity?: string;
  /** Time column → with regEntity, emit full panel regression (plm/linearmodels). */
  regTime?: string;
}

const NA_TOKENS = [
  "",
  "NA",
  "na",
  "N/A",
  "n/a",
  "null",
  "NULL",
  "NaN",
  "nan",
  "-",
  "?",
];

const py = (name: string) => JSON.stringify(name); // safe double-quoted

// ---------------------------------------------------------------------------
// Python (pandas)
// ---------------------------------------------------------------------------

function pyAction(a: CleaningAction): string[] {
  switch (a.op) {
    case "dropDuplicates":
      return ["df = df.drop_duplicates()"];
    case "dropColumn":
      return [`df = df.drop(columns=[${py(a.column)}])`];
    case "normalizeCategory":
      return [
        `_s = df[${py(a.column)}].astype("string").str.strip()`,
        `df[${py(a.column)}] = _s.groupby(_s.str.lower()).transform(lambda x: x.value_counts().idxmax())`,
      ];
    case "fillMissing":
      if (a.strategy === "drop")
        return [`df = df.dropna(subset=[${py(a.column)}])`];
      if (a.strategy === "mode")
        return [
          `df[${py(a.column)}] = df[${py(a.column)}].fillna(df[${py(a.column)}].mode().iloc[0])`,
        ];
      return [
        `df[${py(a.column)}] = df[${py(a.column)}].fillna(df[${py(a.column)}].${a.strategy}())`,
      ];
  }
}

export function generatePython(o: CodegenOptions): string {
  const L: string[] = [];
  L.push("# Reproducible analysis generated by ceritabel");
  L.push(`# Dataset: ${o.fileName}`);
  L.push("import pandas as pd");
  L.push("");
  L.push(`NA = ${JSON.stringify(NA_TOKENS)}`);
  if (o.isExcel) {
    const sheet = o.sheetName ? `, sheet_name=${py(o.sheetName)}` : "";
    L.push(`df = pd.read_excel(${py(o.fileName)}${sheet}, na_values=NA)`);
  } else {
    L.push(`df = pd.read_csv(${py(o.fileName)}, na_values=NA, keep_default_na=True)`);
  }
  L.push("");

  if (o.excluded.length > 0) {
    L.push("# Select variables (drop the ones you excluded)");
    L.push(`df = df.drop(columns=${JSON.stringify(o.excluded)})`);
    L.push("");
  }

  if (o.actions.length > 0) {
    L.push("# Cleaning steps (same order as in the app)");
    for (const a of o.actions) L.push(...pyAction(a));
    L.push("");
  }

  L.push("# Exploratory data analysis");
  L.push("print(df.shape)");
  L.push("print(df.dtypes)");
  L.push('print(df.describe(include="all"))');
  L.push("print(df.isna().sum())");
  L.push('print(df.select_dtypes("number").corr())  # Pearson, pairwise');
  L.push("");

  L.push("# Visualizations");
  L.push("import matplotlib.pyplot as plt");
  L.push('num = df.select_dtypes("number")');
  L.push("num.hist(figsize=(11, 7)); plt.tight_layout(); plt.show()  # histograms");
  L.push("if num.shape[1] >= 2:");
  L.push('    plt.imshow(num.corr(), cmap="coolwarm", vmin=-1, vmax=1)');
  L.push("    plt.colorbar(); plt.xticks(range(num.shape[1]), num.columns, rotation=90)");
  L.push('    plt.yticks(range(num.shape[1]), num.columns); plt.title("Correlation"); plt.show()');
  L.push("");

  if (o.shape === "timeseries" && o.timeCol && o.valueCol) {
    L.push("# Time series");
    L.push(`ts = df[[${py(o.timeCol)}, ${py(o.valueCol)}]].dropna().sort_values(${py(o.timeCol)})`);
    L.push(`ts["ma"] = ts[${py(o.valueCol)}].rolling(${o.maWindow ?? 3}).mean()`);
    L.push("print(ts.tail())");
    L.push(`ts.set_index(${py(o.timeCol)})[[${py(o.valueCol)}, "ma"]].plot(title="Time series"); plt.show()`);
  } else if (o.shape === "panel" && o.entityCol && o.valueCol) {
    L.push("# Panel: within/between decomposition (xtsum-style)");
    L.push(`g = df.groupby(${py(o.entityCol)})[${py(o.valueCol)}]`);
    L.push("between_sd = g.mean().std()");
    L.push(`within_sd = (df[${py(o.valueCol)}] - g.transform("mean")).std()`);
    L.push('print("between SD:", between_sd, "| within SD:", within_sd)');
    L.push(`df.boxplot(column=${py(o.valueCol)}, by=${py(o.entityCol)}); plt.show()`);
  }

  if (o.regTarget && o.regEntity && o.regTime) {
    L.push("");
    L.push("# Panel regression: pooled / fixed / random effects + Hausman");
    L.push("# needs: pip install linearmodels");
    L.push("from linearmodels.panel import PanelOLS, RandomEffects, PooledOLS");
    L.push("import statsmodels.api as sm");
    L.push(`pdf = df.set_index([${py(o.regEntity)}, ${py(o.regTime)}])`);
    L.push('num = pdf.select_dtypes("number")');
    L.push(`xs = [c for c in num.columns if c != ${py(o.regTarget)}]`);
    L.push("exog = sm.add_constant(num[xs])");
    L.push(`fe = PanelOLS(num[${py(o.regTarget)}], exog, entity_effects=True).fit()`);
    L.push(`re = RandomEffects(num[${py(o.regTarget)}], exog).fit()`);
    L.push(`pooled = PooledOLS(num[${py(o.regTarget)}], exog).fit()`);
    L.push("print(fe);  print(re)  # compare; choose via Hausman test");
  } else if (o.regTarget && o.regEntity) {
    L.push("");
    L.push(`# Fixed-effects regression: ${o.regTarget} ~ predictors + entity FE`);
    L.push("import statsmodels.formula.api as smf");
    L.push(`xs = [c for c in df.select_dtypes("number").columns if c not in [${py(o.regTarget)}, ${py(o.regEntity)}]]`);
    L.push(`formula = ${py(o.regTarget)} + " ~ " + " + ".join(xs) + " + C(" + ${py(o.regEntity)} + ")"`);
    L.push("print(smf.ols(formula, data=df).fit().summary())  # entity fixed effects");
  } else if (o.regTarget) {
    L.push("");
    L.push(`# Multiple regression (OLS): factors affecting ${o.regTarget}`);
    L.push("import statsmodels.api as sm");
    L.push('num = df.select_dtypes("number").dropna()');
    L.push(`y = num[${py(o.regTarget)}]`);
    L.push(`X = sm.add_constant(num.drop(columns=[${py(o.regTarget)}]))`);
    L.push("m = sm.OLS(y, X).fit()");
    L.push("print(m.summary())  # joint F-test + partial t-tests");
    L.push("");
    L.push("# Classical assumptions");
    L.push("from statsmodels.stats.diagnostic import het_breuschpagan");
    L.push("from statsmodels.stats.stattools import durbin_watson, jarque_bera");
    L.push("from statsmodels.stats.outliers_influence import variance_inflation_factor");
    L.push("print('Jarque-Bera (normality):', jarque_bera(m.resid))");
    L.push("print('Breusch-Pagan p (hetero):', het_breuschpagan(m.resid, X)[1])");
    L.push("print('Durbin-Watson (autocorr):', durbin_watson(m.resid))");
    L.push("print('VIF:', {c: variance_inflation_factor(X.values, i) for i, c in enumerate(X.columns)})");
  }

  return L.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// R (base + dplyr)
// ---------------------------------------------------------------------------

function rAction(a: CleaningAction): string[] {
  if (a.op === "dropDuplicates") return ["df <- df[!duplicated(df), ]"];
  const c = JSON.stringify(a.column);
  switch (a.op) {
    case "dropColumn":
      return [`df[[${c}]] <- NULL`];
    case "normalizeCategory":
      return [
        `df[[${c}]] <- trimws(df[[${c}]])`,
        `.canon <- tapply(df[[${c}]], tolower(df[[${c}]]), function(v) names(sort(table(v), decreasing = TRUE))[1])`,
        `df[[${c}]] <- unname(.canon[tolower(df[[${c}]])])`,
      ];
    case "fillMissing":
      if (a.strategy === "drop") return [`df <- df[!is.na(df[[${c}]]), ]`];
      if (a.strategy === "mode")
        return [`df[[${c}]][is.na(df[[${c}]])] <- .mode(df[[${c}]])`];
      return [
        `df[[${c}]][is.na(df[[${c}]])] <- ${a.strategy}(df[[${c}]], na.rm = TRUE)`,
      ];
  }
}

export function generateR(o: CodegenOptions): string {
  const L: string[] = [];
  const usesMode = o.actions.some(
    (a) => a.op === "fillMissing" && a.strategy === "mode",
  );
  L.push("# Reproducible analysis generated by ceritabel");
  L.push(`# Dataset: ${o.fileName}`);
  if (o.isExcel) L.push("library(readxl)");
  L.push("");
  if (usesMode) {
    L.push("# helper: most frequent value (mode)");
    L.push(".mode <- function(x) { ux <- unique(x[!is.na(x)]); ux[which.max(tabulate(match(x, ux)))] }");
    L.push("");
  }
  L.push(`na <- ${rVec(NA_TOKENS)}`);
  if (o.isExcel) {
    const sheet = o.sheetName ? `, sheet = ${JSON.stringify(o.sheetName)}` : "";
    L.push(`df <- as.data.frame(read_excel(${JSON.stringify(o.fileName)}${sheet}, na = na))`);
  } else {
    L.push(`df <- read.csv(${JSON.stringify(o.fileName)}, na.strings = na, stringsAsFactors = FALSE)`);
  }
  L.push("");

  if (o.excluded.length > 0) {
    L.push("# Select variables (drop the ones you excluded)");
    L.push(`df <- df[, !(names(df) %in% ${rVec(o.excluded)})]`);
    L.push("");
  }

  if (o.actions.length > 0) {
    L.push("# Cleaning steps (same order as in the app)");
    for (const a of o.actions) L.push(...rAction(a));
    L.push("");
  }

  L.push("# Exploratory data analysis");
  L.push("str(df)");
  L.push("summary(df)");
  L.push("colSums(is.na(df))");
  L.push('cor(df[sapply(df, is.numeric)], use = "pairwise.complete.obs")  # Pearson');
  L.push("");

  L.push("# Visualizations");
  L.push("library(ggplot2)");
  L.push("num <- df[sapply(df, is.numeric)]");
  L.push("for (col in names(num)) {");
  L.push("  print(ggplot(df, aes(.data[[col]])) + geom_histogram(bins = 30) + labs(title = col))");
  L.push("}");
  L.push('if (ncol(num) >= 2) heatmap(cor(num, use = "pairwise.complete.obs"), Rowv = NA, Colv = NA, scale = "none", main = "Correlation")');
  L.push("");

  if (o.shape === "timeseries" && o.timeCol && o.valueCol) {
    const tc = JSON.stringify(o.timeCol);
    const vc = JSON.stringify(o.valueCol);
    L.push("# Time series");
    L.push(`ts <- df[order(df[[${tc}]]), c(${tc}, ${vc})]`);
    L.push(`ts <- ts[!is.na(ts[[${vc}]]), ]`);
    L.push(`ts$ma <- stats::filter(ts[[${vc}]], rep(1/${o.maWindow ?? 3}, ${o.maWindow ?? 3}), sides = 1)`);
    L.push("tail(ts)");
    L.push(`print(ggplot(ts, aes(seq_len(nrow(ts)), .data[[${vc}]])) + geom_line() + labs(title = "Time series", x = "index", y = ${vc}))`);
  } else if (o.shape === "panel" && o.entityCol && o.valueCol) {
    const ec = JSON.stringify(o.entityCol);
    const vc = JSON.stringify(o.valueCol);
    L.push("# Panel: within/between decomposition");
    L.push(`emean <- tapply(df[[${vc}]], df[[${ec}]], mean, na.rm = TRUE)`);
    L.push("between_sd <- sd(emean, na.rm = TRUE)");
    L.push(`within_sd <- sd(df[[${vc}]] - emean[as.character(df[[${ec}]])], na.rm = TRUE)`);
    L.push('cat("between SD:", between_sd, "| within SD:", within_sd, "\\n")');
    L.push(`print(ggplot(df, aes(factor(.data[[${ec}]]), .data[[${vc}]])) + geom_boxplot() + labs(x = ${ec}, y = ${vc}))`);
  }

  if (o.regTarget && o.regEntity && o.regTime) {
    const yq = JSON.stringify(o.regTarget);
    const eq = JSON.stringify(o.regEntity);
    const tq = JSON.stringify(o.regTime);
    L.push("");
    L.push("# Panel regression: pooled / fixed / random effects + Hausman");
    L.push("# needs: install.packages('plm')");
    L.push("library(plm)");
    L.push(`xs <- setdiff(names(df)[sapply(df, is.numeric)], c(${yq}, ${eq}, ${tq}))`);
    L.push(`f <- reformulate(xs, response = ${yq})`);
    L.push(`pdata <- pdata.frame(df, index = c(${eq}, ${tq}))`);
    L.push('pooled <- plm(f, pdata, model = "pooling")');
    L.push('fe <- plm(f, pdata, model = "within")   # fixed effects');
    L.push('re <- plm(f, pdata, model = "random")   # random effects');
    L.push("summary(fe); summary(re)");
    L.push("phtest(fe, re)   # Hausman test: significant -> use fixed effects");
  } else if (o.regTarget && o.regEntity) {
    const yq = JSON.stringify(o.regTarget);
    const eq = JSON.stringify(o.regEntity);
    L.push("");
    L.push(`# Fixed-effects regression (LSDV): ${o.regTarget} ~ predictors + factor(${o.regEntity})`);
    L.push(`xs <- setdiff(names(df)[sapply(df, is.numeric)], c(${yq}, ${eq}))`);
    L.push(`fit <- lm(reformulate(c(xs, sprintf("factor(\`%s\`)", ${eq})), response = ${yq}), data = df)`);
    L.push("summary(fit)  # entity fixed effects (within estimator)");
  } else if (o.regTarget) {
    const yq = JSON.stringify(o.regTarget);
    L.push("");
    L.push(`# Multiple regression (OLS): factors affecting ${o.regTarget}`);
    L.push("num <- df[sapply(df, is.numeric)]");
    L.push(`fit <- lm(num[[${yq}]] ~ ., data = num[, setdiff(names(num), ${yq})])`);
    L.push("summary(fit)  # joint F-test + partial t-tests");
    L.push("");
    L.push("# Classical assumptions  (needs: install.packages(c('lmtest','car','tseries')))");
    L.push("library(lmtest); library(car); library(tseries)");
    L.push("jarque.bera.test(resid(fit))   # normality");
    L.push("vif(fit)                        # multicollinearity");
    L.push("bptest(fit)                     # heteroscedasticity");
    L.push("dwtest(fit)                     # autocorrelation");
  }

  return L.join("\n") + "\n";
}

function rVec(arr: string[]): string {
  return `c(${arr.map((s) => JSON.stringify(s)).join(", ")})`;
}
